"""Generador de datos de entrenamiento para el clasificador neuronal.

Genera muestras sintéticas de alta calidad para las 17 categorías académicas
usando patrones realistas de documentos universitarios.
"""

from __future__ import annotations

import random
from typing import Final

CATEGORIES: Final[list[str]] = [
    "Inteligencia Artificial",
    "Base de Datos",
    "Administracion de Redes",
    "Hacking Etico",
    "Tecnologias de Virtualizacion",
    "Tecnologias en la Nube",
    "Taller de Investigacion",
    "Programacion Logica y Funcional",
    "Desarrollo Web",
    "Desarrollo Movil",
    "Desarrollo de Software",
    "Ciberseguridad",
    "Ciencia de Datos",
    "Arquitectura de Computadoras",
    "Sistemas Operativos",
    "Matematicas Discretas",
    "Estadistica",
]

CATEGORY_PATTERNS: Final[dict[str, list[str]]] = {
    "Inteligencia Artificial": [
        "red neuronal convolucional CNN arquitectura deep learning",
        "algoritmo machine learning supervised unsupervised classification regression",
        "tensorflow pytorch keras neural network perceptron backpropagation",
        "natural language processing NLP transformer BERT GPT embeddings",
        "computer vision object detection YOLO segmentation facial recognition",
        "reinforcement learning Q-learning DQN policy gradient reward",
        "clustering K-means DBSCAN hierarchical dimensionality reduction PCA",
        "decision tree random forest XGBoost gradient boosting ensemble",
        "overfitting underfitting regularization dropout batch normalization",
        "generative adversarial network GAN VAE diffusion model image generation",
        "recurrent neural network LSTM GRU sequential data time series",
        "transfer learning fine-tuning pretrained model huggingface",
        "convolutional neural network feature extraction pooling layer",
        "optimization adam sgd gradient descent learning rate",
        "data augmentation synthetic training dataset imbalance",
        "evaluation metrics accuracy precision recall F1-score AUC ROC",
        "recommendation system collaborative filtering content-based",
        "neural architecture search AutoML hyperparameter tuning",
        "quantum machine learning quantum computing AI intersection",
        "explainable AI interpretability SHAP LIME feature importance",
    ],
    "Base de Datos": [
        "MySQL PostgreSQL Oracle MariaDB relational database management system",
        "SQL query join inner outer left right natural full cross",
        "normalization 1NF 2NF 3NF BCNF database design entity relationship",
        "index primary key foreign unique constraint check violation",
        "transaction commit rollback savepoint ACID isolation level",
        "NoSQL MongoDB Redis Cassandra document key-value wide-column",
        "stored procedure function trigger view materialized query optimization",
        "database replication clustering failover high availability sharding",
        "SQL injection prevention parameterized prepared statement ORM",
        "data warehouse ETL pipeline ELT data lake warehouse lakehouse",
        "CAP theorem eventual consistency partition tolerance distributed",
        "MongoDB aggregation pipeline map-reduce indexing schema design",
        "database backup restore recovery point-in-time disaster recovery",
        "connection pool concurrency lock deadlock isolation transaction",
        "SQL performance tuning explain plan query optimization index",
        "database security authentication authorization audit compliance",
        "graph database Neo4j Cypher relationship traversal",
        "time-series database InfluxDB Prometheus metrics storage",
        "database migration schema versioning Liquibase Flyway",
        "full-text search Elasticsearch Lucene indexing document",
    ],
    "Administracion de Redes": [
        "TCP IP UDP ICMP IPv4 IPv6 protocol suite network layer",
        "subnet mask CIDR VLSM network address calculation VLAN",
        "router switch gateway default route static dynamic routing OSPF BGP",
        "DNS DHCP NAT PAT port forwarding address translation",
        "Cisco CCNA CCNP routing switching network configuration",
        "wireless WiFi WLAN 802.11 access point hotspot WPA2 WPA3",
        "network topology star ring bus mesh hybrid architecture",
        "firewall ACL VPN IPSec tunnel GRE MPLS tunneling",
        "SNMP monitoring Nagios Zabbix Prometheus network management",
        "traceroute ping netstat ipconfig ifconfig network diagnostic",
        "load balancer CDN proxy reverse proxy traffic distribution",
        "network security firewall IDS IPS penetration testing",
        "bandwidth throughput latency jitter packet loss QoS",
        "VLAN trunking 802.1Q inter-VLAN routing switchport mode",
        "network virtualization SDN OpenFlow controller data plane",
        "ARP MAC address resolution ethernet frame switching",
        "multicast broadcast unicast IGMP protocol handling",
        "network troubleshooting packet capture Wireshark analysis",
        "VPN configuration site-to-site remote access OpenVPN WireGuard",
        "ISP BGP peering autonomous system transit route",
    ],
    "Hacking Etico": [
        "penetration testing pentest vulnerability assessment exploitation",
        "metasploit msfconsole msfvenom payload meterpreter handler",
        "Nmap Zenmap port scanning fingerprinting OS detection",
        "OWASP Top 10 web application security vulnerability CVE",
        "SQL injection XSS CSRF SSRF LFI RFI XXE attack vectors",
        "buffer overflow format string integer overflow memory corruption",
        "reverse engineering malware analysis forensic investigation",
        "Kali Linux penetration testing distribution BackBox Parrot",
        "Burp Suite OWASP ZAP web proxy security testing",
        "password cracking hashcat John the Ripper credential attack",
        "privilege escalation privesc windows linux kernel exploit",
        "pivoting lateral movement network segmentation bypass",
        "social engineering phishing spearphishing whaling vishing",
        "wireless security WEP WPA2 WPA3 WPS penetration testing",
        "red team purple team adversary emulation threat hunting",
        "CTF capture the flag competition hacking challenge",
        "digital forensics incident response SIEM log analysis",
        "zero-day exploit vulnerability disclosure bug bounty",
        "post-exploitation persistence implant C2 beaconing",
        "cover tracks log tampering forensic anti-forensics",
    ],
    "Tecnologias de Virtualizacion": [
        "VMware vSphere ESXi vCenter virtual machine VM snapshot",
        "Docker container Dockerfile docker-compose podman containerd",
        "Kubernetes K8s pod service deployment replicaSet ingress",
        "VirtualBox hypervisor type1 type2 bare-metal hosted",
        "hypervisor architecture virtualization technology KVM QEMU",
        "container orchestration Docker Swarm Kubernetes Helm chart",
        "VM migration live migration vMotion storage vMotion",
        "vagrant packer infrastructure as code VM provisioning",
        "Proxmox VE open-source virtualization platform Ceph storage",
        "VMWare Workstation Fusion desktop virtualization",
        "nested virtualization VM inside VM performance overhead",
        "virtual network bridge NAT host-only internal networking",
        "container networking bridge host overlay Macvlan Calico",
        "image template VM cloning golden image management",
        "disk format VMDK VHDX QCOW2 raw image conversion",
        "virtualization security hypervisor breakout VM escape",
        "resource allocation CPU memory disk quota limit reservation",
        "cloud-init user-data provisioning VM initialization",
        "volume mount container storage Docker volume bind mount",
        "libvirt KVM virsh virt-manager virtualization API",
    ],
    "Tecnologias en la Nube": [
        "AWS Amazon Web Services EC2 S3 Lambda ECS EKS RDS DynamoDB",
        "Microsoft Azure virtual machine App Service Functions CosmosDB",
        "Google Cloud Platform GCP Compute Engine Cloud Storage BigQuery",
        "cloud computing IaaS PaaS SaaS FaaS serverless architecture",
        "AWS Lambda Azure Functions Google Cloud Functions serverless",
        "cloud storage S3 bucket blob storage CDN CloudFront",
        "container registry ECR ACR GCR image push pull",
        "Kubernetes managed EKS AKS GKE GKE Autopilot cloud provider",
        "cloud networking VPC subnet security group firewall rule",
        "IAM role policy permission AWS Identity Azure AD GCP IAM",
        "Terraform CloudFormation infrastructure as code IaC",
        "serverless framework SAM AWS CDK serverless application",
        "microservices architecture API gateway service mesh Istio",
        "cloud monitoring CloudWatch Azure Monitor Stackdriver",
        "CI/CD pipeline CodeBuild CodeDeploy CodePipeline GitHub Actions",
        "cloud cost optimization reserved instance savings plan",
        "disaster recovery DR backup multi-region redundancy",
        "cloud security compliance SOC2 HIPAA GDPR encryption",
        "ELB ALB NLB load balancing autoscaling scaling policy",
        "serverless database Aurora Serverless DynamoDB On-Demand",
    ],
    "Taller de Investigacion": [
        "tesis investigacion metodologia cientifica proyecto academico",
        "hipotesis objetivo justificacion alcance delimitacion",
        "marco teorico conceptual antecedentes literature review",
        "metodologia investigacion cualitativa cuantitativa mixta",
        "analisis de resultados datos estadisticos interpretacion",
        "conclusiones recomendaciones trabajo terminal graduation",
        "formatos APA MLA Chicago citation bibliography reference",
        "proyecto integral desarrollo solucion problema real",
        "protocolo investigacion validacion instrumentos medicion",
        "muestra poblacion muestreo aleatorio sistemtico estratificado",
        "entrevista encuesta cuestionario observacion investigacion",
        "articulo cientifico publicacion journal peer review",
        "resumen abstract introduccion desarrollo conclusion",
        "informe tecnico reporte documentacion tecnica",
        "presentacion exposicion defensa proyecto slides",
        "fuentes informacion bibliografica hemeroteca archivo",
        "analisis documental fuentes primarias secundarias",
        "diseño no experimental experimental quasi-experimental",
        "variable dependiente independiente controlada",
        "validez confiabilidad instrumento medicion investigacion",
    ],
    "Programacion Logica y Funcional": [
        "Prolog logic programming predicate clause fact rule",
        "Haskell functional programming monad functor applicative",
        "Lisp Scheme Common Lisp emacs elisp programming language",
        "Erlang Elixir functional concurrent programming OTP",
        "Clojure JVM functional programming immutable data",
        "recursion tail recursion accumulator optimization",
        "lambda calculus closure currying partial application",
        "pattern matching unification backtracking search",
        "immutable data structures persistent functional",
        "lazy evaluation eager evaluation monad IO maybe either",
        "type inference Hindley-Milner parametric polymorphism",
        "declarative programming imperative vs declarative",
        "higher-order function first-class function composition",
        "F# functional .NET programming language option result",
        "algebraic data type sum type product type record",
        "list comprehension list processing functional operations",
        "map filter reduce fold functional iteration patterns",
        "pure function side effect referential transparency",
        "category theory functor monad programming theory",
        "logic programming Prolog SLD resolution search tree",
    ],
    "Desarrollo Web": [
        "HTML5 CSS3 JavaScript TypeScript frontend development",
        "React Vue Angular Svelte frontend framework library",
        "REST API GraphQL web service endpoint request response",
        "HTTP HTTPS protocol web browser server communication",
        "responsive design mobile-first adaptive CSS framework",
        "Bootstrap Tailwind CSS styling framework component",
        "webpack Vite Rollup esbuild bundler build tool",
        "Node.js Express server-side JavaScript backend",
        "MongoDB Express React Node MERN stack full-stack",
        "authentication JWT OAuth session cookie login",
        "web security XSS CSRF CORS CSP security header",
        "progressive web app PWA service worker offline",
        "single page application SPA routing client-side",
        "state management Redux Vuex Pinia global state",
        "web performance optimization lazy loading code splitting",
        "SEO search engine optimization meta tag semantico",
        "web accessibility WCAG aria screen reader",
        "testing frontend Jest Cypress unit integration e2e",
        "CI/CD deployment Netlify Vercel Heroku cloud hosting",
        "web socket real-time bidirectional communication",
    ],
    "Desarrollo Movil": [
        "Android Studio Kotlin Java mobile development",
        "iOS Swift Xcode Apple development program",
        "Flutter Dart cross-platform mobile framework",
        "React Native JavaScript mobile app development",
        "Kotlin Jetpack Compose Android UI modern toolkit",
        "SwiftUI iOS declarative user interface",
        "mobile app UI UX design material design Cupertino",
        "Gradle Maven build system Android dependency",
        "CocoaPods Swift Package Manager iOS dependency",
        "REST API mobile integration HTTP JSON network",
        "local storage SQLite Room database mobile",
        "push notification FCM APNs Firebase Cloud Messaging",
        "device permission camera location storage runtime",
        "background service worker foreground notification",
        "mobile testing unit instrumented Espresso XCTest",
        "app release Google Play App Store deployment",
        "ProGuard R8 obfuscation release build optimization",
        "ARCore ARKit augmented reality mobile development",
        "mobile security obfuscation certificate pinning",
        "offline-first mobile architecture sync strategy",
    ],
    "Desarrollo de Software": [
        "agile scrum kanban sprint retrospective daily standup",
        "UML diagram use case class sequence activity diagram",
        "software requirement specification SRS functional non-functional",
        "testing unit integration e2e automated test TDD BDD",
        "design pattern singleton factory observer strategy decorator",
        "SOLID principles single responsibility open closed liskov interface segregation dependency inversion",
        "version control Git GitHub GitLab branch merge pull request",
        "code review peer review approval feedback refactoring",
        "technical debt refactoring code smell improvement",
        "continuous integration CI continuous delivery CD pipeline",
        "software architecture microservices monolith layered hexagonal",
        "REST API design best practice resource naming versioning",
        "ORM object relational mapping database abstraction",
        "dependency injection IoC container inversion control",
        "software testing black box white box smoke regression",
        "project management Jira Trello board sprint planning",
        "DevOps culture collaboration automation measurement",
        "logging monitoring error tracking Sentry Datadog",
        "documentation README API doccode generation",
        "software estimation effort planning story point Fibonacci",
    ],
    "Ciberseguridad": [
        "cibersecurity network security information security",
        "encryption AES RSA SHA hashing cryptographic algorithm",
        "firewall WAF IDS IPS network security appliance",
        "authentication authorization OAuth2 SAML SSO identity",
        "LDAP Active Directory Kerberos authentication protocol",
        "malware virus trojan ransomware spyware protection",
        "phishing social engineering security awareness training",
        "incident response forensics evidence collection SIEM",
        "vulnerability management CVE NVD patch management",
        "security framework NIST ISO 27001 compliance audit",
        "zero trust architecture network segmentation microsegmentation",
        "penetration testing red team ethical hacking",
        "web application security OWASP secure coding",
        "cloud security shared responsibility CSPM CWPP",
        "security operations center SOC alert triage escalation",
        "threat intelligence IOC SIEM threat hunting",
        "cryptography public key private key certificate PKI",
        "DDoS attack mitigation rate limiting CDN protection",
        "mobile security MDM MAM enterprise mobility",
        "security awareness phishing simulation training",
    ],
    "Ciencia de Datos": [
        "data science analytics exploratory data analysis EDA",
        "pandas numpy scipy data manipulation python library",
        "big data Hadoop Spark distributed processing framework",
        "data visualization matplotlib seaborn Plotly tableau dashboard",
        "machine learning supervised unsupervised semi-supervised",
        "regression linear logistic polynomial model prediction",
        "classification decision tree random forest SVM naive bayes",
        "clustering K-means hierarchical DBSCAN segmentation",
        "dimensionality reduction PCA t-SNE UMAP feature extraction",
        "natural language processing text mining NLP sentiment analysis",
        "time series forecasting ARIMA Prophet LSTM prediction",
        "feature engineering selection extraction transformation scaling",
        "model evaluation cross-validation hyperparameter tuning",
        "deep learning neural network tensorflow pytorch keras",
        "data warehouse ETL pipeline airflow databricks lakehouse",
        "statistics descriptive inferential hypothesis testing",
        "A/B testing experiment design statistical significance",
        "recommendation system collaborative filtering content-based",
        "image computer vision convolutional neural network CNN",
        "big data streaming Spark Streaming Flink real-time",
    ],
    "Arquitectura de Computadoras": [
        "CPU processor architecture instruction set ISA x86 ARM",
        "GPU graphics processing unit CUDA parallel computing",
        "memory RAM DRAM SRAM cache L1 L2 L3 hierarchy",
        "assembly language MASM NASM GAS assembler instruction",
        "register program counter stack pointer accumulator",
        "bus system address bus data bus control bus",
        "pipeline instruction hazard stall bubble branch prediction",
        " ALU arithmetic logic unit CU control unit processor",
        "interrupt DMA direct memory access I/O operation",
        "virtual memory paging segmentation TLB MMU",
        "cache mapping direct associative set-associative",
        "instruction format opcode operand addressing mode",
        "microarchitecture processor design circuit optimization",
        "parallel processing multicore multiprocessor symmetric",
        "FPGA field programmable gate array Verilog VHDL",
        "RISC CISC instruction set complexity reduced complex",
        "embedded system microcontroller firmware hardware software",
        "clock frequency timing cycle performance optimization",
        "power consumption thermal management processor efficiency",
        "computer system bus architecture peripheral device",
    ],
    "Sistemas Operativos": [
        "operating system kernel process thread scheduling",
        "Linux Ubuntu Debian CentOS RedHat distribution",
        "Windows Server desktop OS Windows 10 11",
        "Unix FreeBSD OpenBSD system call syscall interface",
        "process management fork exec wait zombie orphan",
        "thread synchronization mutex semaphore critical section",
        "deadlock starvation priority inversion resource allocation",
        "memory management virtual memory swap paging allocation",
        "file system NTFS ext4 Btrfs ZFS filesystem",
        "shell bash zsh fish command line terminal",
        "kernel module driver device hardware abstraction",
        "scheduling algorithm FCFS SJF round-robin priority",
        "multitasking multiprogramming time-sharing real-time",
        "system initialization boot loader GRUB UEFI BIOS",
        "process communication IPC pipe message queue shared memory",
        "user management permission root sudo access control",
        "network stack TCP IP socket programming BSD",
        "virtualization container runtime Docker container",
        "system monitoring top htop ps kill resource usage",
        "service management systemd init daemon service",
    ],
    "Matematicas Discretas": [
        "discrete mathematics logic propositional predicate",
        "set theory union intersection complement Venn diagram",
        "relation function mapping domain codomain injection surjection",
        "graph theory vertex edge node path cycle tree",
        "graph algorithm BFS DFS breadth-first depth-first search",
        "Dijkstra shortest path algorithm minimum spanning tree",
        "Kruskal Prim graph algorithm network flow",
        "boolean algebra gate circuit truth table simplification",
        "combinatorics permutation combination counting principle",
        "recurrence relation recursion induction mathematical proof",
        "tree data structure binary tree BST heap trie",
        "topological sort DAG directed acyclic graph ordering",
        "modular arithmetic congruence GCD LCM prime number",
        "pigeonhole principle inclusion exclusion counting",
        "automata theory finite state machine regular expression",
        "Turing machine computability complexity NP complete",
        "logic gate NAND NOR XOR boolean function minimization",
        "Karnaugh map Quine-McCluskey simplification method",
        "binomial theorem Pascal triangle coefficient expansion",
        "graph isomorphism homomorphism subgraph connectivity",
    ],
    "Estadistica": [
        "statistics descriptive mean median mode variance standard deviation",
        "probability distribution normal binomial Poisson exponential",
        "hypothesis testing null alternative p-value significance",
        "confidence interval estimation population parameter",
        "regression analysis linear correlation coefficient",
        "ANOVA analysis variance between groups within groups",
        "Bayesian statistics prior posterior likelihood inference",
        "sampling technique random systematic stratified cluster",
        "chi-square test independence goodness of fit",
        "t-test student independent paired sample comparison",
        "non-parametric test Wilcoxon Mann-Whitney Kruskal",
        "correlationPearson Spearman rank bivariate analysis",
        "statistical software R Python statistics library",
        "sample size determination power analysis effect size",
        "central limit theorem normal approximation distribution",
        "data transformation logarithm square root normalization",
        "outlier detection treatment missing value imputation",
        "multivariate analysis factor analysis PCA component",
        "time series analysis trend seasonal decomposition",
        "experimental design randomized block factorial design",
    ],
}

DOCUMENT_TYPES: Final[list[str]] = [
    "proyecto final",
    "reporte",
    "practica",
    "tarea",
    "examen",
    "apuntes",
    "presentacion",
    "ensayo",
    "tesis",
    "monografia",
    "resumen",
    "guia estudio",
    "laboratorio",
    "caso estudio",
    "investigacion",
]

ACADEMIC_TERMS: Final[list[str]] = [
    "universidad", "instituto", "tecnologico", "carrera", "semestre",
    "maestro", "profesor", "docente", "alumno", "estudiante",
    "calificacion", "credito", "materia", "asignatura", "unidad",
    "biblioteca", "laboratorio", "aula", "campus", "exposicion",
    "equipo", "grupo", "colaboracion", "integrantes",
    "introduccion", "objetivos", "metodologia", "resultados",
    "conclusiones", "referencias", "anexos", "apendice",
]

random.seed(42)


def generate_category_samples(category: str, count: int = 30) -> list[tuple[str, str]]:
    """Genera muestras de entrenamiento para una categoría."""
    patterns = CATEGORY_PATTERNS.get(category, [])
    if not patterns:
        return []

    samples = []
    for _ in range(count):
        base_pattern = random.choice(patterns)
        doc_type = random.choice(DOCUMENT_TYPES)
        academic_term = random.choice(ACADEMIC_TERMS)
        semester = random.choice(["primer", "segundo", "tercer", "cuarto", "quinto", "sexto"])

        variants = [
            f"{category} {base_pattern}",
            f"{category} {doc_type} {base_pattern}",
            f"{doc_type} {category} {base_pattern}",
            f"{academic_term} {category} {base_pattern}",
            f"materia {category} {semester} semestre {base_pattern}",
            f"proyecto {category} {base_pattern}",
            f"portada {category} {doc_type} {base_pattern}",
            f"trabajo {category} {academic_term} {base_pattern}",
            f"{base_pattern} {category}",
            f"reporte final {category} {base_pattern}",
        ]
        text = random.choice(variants)
        samples.append((text, category))

    return samples


def generate_all_samples(extra_samples_per_category: int = 30) -> list[tuple[str, str]]:
    """Genera todas las muestras de entrenamiento para el clasificador."""
    all_samples = []

    for category in CATEGORIES:
        category_samples = generate_category_samples(category, extra_samples_per_category)
        all_samples.extend(category_samples)

    return all_samples


def get_training_corpus() -> dict[str, list[str]]:
    """Retorna un diccionario de categoría -> textos de entrenamiento."""
    corpus = {}
    for category in CATEGORIES:
        patterns = CATEGORY_PATTERNS.get(category, [])
        corpus[category] = patterns
    return corpus


if __name__ == "__main__":
    samples = generate_all_samples(20)
    print(f"Total samples generated: {len(samples)}")
    for cat in CATEGORIES:
        count = sum(1 for _, label in samples if label == cat)
        print(f"  {cat}: {count}")